/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"

double *
sumar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1 + arg2;

	return &result;
}

double *
restar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1 - arg2;

	return &result;
}

double *
multiplicar_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1 * arg2;

	return &result;
}

double *
dividir_1_svc(double arg1, double arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = arg1 / arg2;

	return &result;
}

double *
escalar_1_svc(vect2 arg1, vect2 arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1->x * arg2->x) + (arg1->y * arg2->y);

	return &result;
}

vect2 *
vectorial_1_svc(vect2 arg1, vect2 arg2,  struct svc_req *rqstp)
{
	static vect2  result;

	result->x = (arg1->x * arg2->y) - (arg2->x * arg1->y);
	result->y = 0;

	return &result;
}

double *
escalar_1_svc(vect3 arg1, vect3 arg2,  struct svc_req *rqstp)
{
	static double  result;

	result = (arg1->x * arg2->x) + (arg1->y * arg2->y) + (arg1->z * arg2->z);

	return &result;
}

vect3 *
vectorial_1_svc(vect3 arg1, vect3 arg2,  struct svc_req *rqstp)
{
	static vect3  result;

	result->x = (arg1->y * arg2->z) - (arg2->y * arg1->z);
	result->y = (arg1->z * arg2->x) - (arg2->z * arg1->x);
	result->x = (arg1->x * arg2->y) - (arg2->x * arg1->y);

	return &result;
}
