/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	double sumar_1_arg1;
	double sumar_1_arg2;
	double  *result_2;
	double restar_1_arg1;
	double restar_1_arg2;
	double  *result_3;
	double multiplicar_1_arg1;
	double multiplicar_1_arg2;
	double  *result_4;
	double dividir_1_arg1;
	double dividir_1_arg2;
	double  *result_5;
	vect2  escalar_1_arg1;
	vect2  escalar_1_arg2;
	vect2  *result_6;
	vect2  vectorial_1_arg1;
	vect2  vectorial_1_arg2;
	double  *result_7;
	vect3  escalar_1_arg1;
	vect3  escalar_1_arg2;
	vect3  *result_8;
	vect3  vectorial_1_arg1;
	vect3  vectorial_1_arg2;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCPROG, CALCVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	printf("\t1. Suma de numeros\n");
	printf("\t2. Resta de numeros\n");
	printf("\t3. Multiplicacion de numeros\n");
	printf("\t4. Division de numeros\n");
	printf("\t5. Escalar de vector 2D\n");
	printf("\t6. Vectorial de vector 2D\n");
	printf("\t7. Escalar de vector 3D\n");
	printf("\t8. Vectorial de vector 3D\n");
	
	int opcion = -1;

	double a, b;
	double *resultado;

	do
	{
		printf("Seleccione una opcion: ");
		scanf("%d", &opcion);
	} while (opcion != 1 && opcion != 2 && opcion != 3 && opcion != 4 && opcion != 5 && opcion != 6 && opcion != 7 && opcion != 8);

	switch (opcion)
	{
	case 1:
		printf("\nIntroduzca el primer numero: ");
		scanf("%lf", &a);
		printf("\nIntroduzca el segundo numero: ");
		scanf("%lf", &b);
		resultado = sumar_1(a, b, clnt);
		if (resultado == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: %g + %g = %g\n", a, b, *resultado);
		break;

	case 2:
		printf("\nIntroduzca el primer numero: ");
		scanf("%lf", &a);
		printf("\nIntroduzca el segundo numero: ");
		scanf("%lf", &b);
		resultado = restar_1(a, b, clnt);
		if (resultado == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: %g - %g = %g\n", a, b, *resultado);
		break;
	
	case 3:
		printf("\nIntroduzca el primer numero: ");
		scanf("%lf", &a);
		printf("\nIntroduzca el segundo numero: ");
		scanf("%lf", &b);
		resultado = multiplicar_1(a, b, clnt);
		if (resultado == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: %g * %g = %g\n", a, b, *resultado);
		break;

	case 4:
		printf("\nIntroduzca el primer numero: ");
		scanf("%lf", &a);
		printf("\nIntroduzca el segundo numero: ");
		scanf("%lf", &b);
		resultado = dividir_1(a, b, clnt);
		if (resultado == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: %g / %g = %g\n", a, b, *resultado);
		break;

	case 5:
		vect2 vectorA, vectorB;
		printf("\nIntroduzca el primer numero del primer vector: ");
		scanf("%lf", &vectorA->x);
		printf("\nIntroduzca el segundo numero del primer vector: ");
		scanf("%lf", &vectorA->y);
		printf("\nIntroduzca el primer numero del primer vector: ");
		scanf("%lf", &vectorB->x);
		printf("\nIntroduzca el segundo numero del primer vector: ");
		scanf("%lf", &vectorB->y);
		resultado = escalar_1(vectorA, vectorB, clnt);
		if (resultado == (double *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: <%g,%g> * <%g,%g> = %g\n", vectorA->x, vectorA->y, vectorB->x, vectorB->y, *resultado);
		break;
	
	case 6:
		vect2 vectorA, vectorB;
		vect2 *vResultado;
		printf("\nIntroduzca el primer numero del primer vector: ");
		scanf("%lf", &vectorA->x);
		printf("\nIntroduzca el segundo numero del primer vector: ");
		scanf("%lf", &vectorA->y);
		printf("\nIntroduzca el primer numero del primer vector: ");
		scanf("%lf", &vectorB->x);
		printf("\nIntroduzca el segundo numero del primer vector: ");
		scanf("%lf", &vectorB->y);
		vResultado = vectorial_1(vectorA, vectorB, clnt);
		if (vResultado == (vect2 *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		printf("Operación: <%g,%g> * <%g,%g> = %g\n", vectorA->x, vectorA->y, vectorB->x, vectorB->y, (*vResultado)->x);
		break;
	
	default:
		break;
	}
	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	calcprog_1 (host);
exit (0);
}
