/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALC_H_RPCGEN
#define _CALC_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct vect2D {
	double x;
	double y;
};
typedef struct vect2D vect2D;

struct vect3D {
	double x;
	double y;
	double z;
};
typedef struct vect3D vect3D;

struct sumar_1_argument {
	double arg1;
	double arg2;
};
typedef struct sumar_1_argument sumar_1_argument;

struct restar_1_argument {
	double arg1;
	double arg2;
};
typedef struct restar_1_argument restar_1_argument;

struct multiplicar_1_argument {
	double arg1;
	double arg2;
};
typedef struct multiplicar_1_argument multiplicar_1_argument;

struct dividir_1_argument {
	double arg1;
	double arg2;
};
typedef struct dividir_1_argument dividir_1_argument;

struct escalar2d_1_argument {
	vect2D arg1;
	vect2D arg2;
};
typedef struct escalar2d_1_argument escalar2d_1_argument;

struct vectorial2d_1_argument {
	vect2D arg1;
	vect2D arg2;
};
typedef struct vectorial2d_1_argument vectorial2d_1_argument;

struct escalar3d_1_argument {
	vect3D arg1;
	vect3D arg2;
};
typedef struct escalar3d_1_argument escalar3d_1_argument;

struct vectorial3d_1_argument {
	vect3D arg1;
	vect3D arg2;
};
typedef struct vectorial3d_1_argument vectorial3d_1_argument;

#define CALCPROG 0x20000000
#define CALCVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  double * sumar_1(double , double , CLIENT *);
extern  double * sumar_1_svc(double , double , struct svc_req *);
#define restar 2
extern  double * restar_1(double , double , CLIENT *);
extern  double * restar_1_svc(double , double , struct svc_req *);
#define multiplicar 3
extern  double * multiplicar_1(double , double , CLIENT *);
extern  double * multiplicar_1_svc(double , double , struct svc_req *);
#define dividir 4
extern  double * dividir_1(double , double , CLIENT *);
extern  double * dividir_1_svc(double , double , struct svc_req *);
#define escalar2D 5
extern  double * escalar2d_1(vect2D , vect2D , CLIENT *);
extern  double * escalar2d_1_svc(vect2D , vect2D , struct svc_req *);
#define vectorial2D 6
extern  double * vectorial2d_1(vect2D , vect2D , CLIENT *);
extern  double * vectorial2d_1_svc(vect2D , vect2D , struct svc_req *);
#define escalar3D 7
extern  double * escalar3d_1(vect3D , vect3D , CLIENT *);
extern  double * escalar3d_1_svc(vect3D , vect3D , struct svc_req *);
#define vectorial3D 8
extern  vect3D * vectorial3d_1(vect3D , vect3D , CLIENT *);
extern  vect3D * vectorial3d_1_svc(vect3D , vect3D , struct svc_req *);
extern int calcprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  double * sumar_1();
extern  double * sumar_1_svc();
#define restar 2
extern  double * restar_1();
extern  double * restar_1_svc();
#define multiplicar 3
extern  double * multiplicar_1();
extern  double * multiplicar_1_svc();
#define dividir 4
extern  double * dividir_1();
extern  double * dividir_1_svc();
#define escalar2D 5
extern  double * escalar2d_1();
extern  double * escalar2d_1_svc();
#define vectorial2D 6
extern  double * vectorial2d_1();
extern  double * vectorial2d_1_svc();
#define escalar3D 7
extern  double * escalar3d_1();
extern  double * escalar3d_1_svc();
#define vectorial3D 8
extern  vect3D * vectorial3d_1();
extern  vect3D * vectorial3d_1_svc();
extern int calcprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vect2D (XDR *, vect2D*);
extern  bool_t xdr_vect3D (XDR *, vect3D*);
extern  bool_t xdr_sumar_1_argument (XDR *, sumar_1_argument*);
extern  bool_t xdr_restar_1_argument (XDR *, restar_1_argument*);
extern  bool_t xdr_multiplicar_1_argument (XDR *, multiplicar_1_argument*);
extern  bool_t xdr_dividir_1_argument (XDR *, dividir_1_argument*);
extern  bool_t xdr_escalar2d_1_argument (XDR *, escalar2d_1_argument*);
extern  bool_t xdr_vectorial2d_1_argument (XDR *, vectorial2d_1_argument*);
extern  bool_t xdr_escalar3d_1_argument (XDR *, escalar3d_1_argument*);
extern  bool_t xdr_vectorial3d_1_argument (XDR *, vectorial3d_1_argument*);

#else /* K&R C */
extern bool_t xdr_vect2D ();
extern bool_t xdr_vect3D ();
extern bool_t xdr_sumar_1_argument ();
extern bool_t xdr_restar_1_argument ();
extern bool_t xdr_multiplicar_1_argument ();
extern bool_t xdr_dividir_1_argument ();
extern bool_t xdr_escalar2d_1_argument ();
extern bool_t xdr_vectorial2d_1_argument ();
extern bool_t xdr_escalar3d_1_argument ();
extern bool_t xdr_vectorial3d_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALC_H_RPCGEN */
