/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calc.h"

bool_t
xdr_vect2D (XDR *xdrs, vect2D *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vect3D (XDR *xdrs, vect3D *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->x))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->y))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->z))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_sumar_1_argument (XDR *xdrs, sumar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_restar_1_argument (XDR *xdrs, restar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_multiplicar_1_argument (XDR *xdrs, multiplicar_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_dividir_1_argument (XDR *xdrs, dividir_1_argument *objp)
{
	 if (!xdr_double (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escalar2d_1_argument (XDR *xdrs, escalar2d_1_argument *objp)
{
	 if (!xdr_vect2D (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect2D (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectorial2d_1_argument (XDR *xdrs, vectorial2d_1_argument *objp)
{
	 if (!xdr_vect2D (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect2D (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_escalar3d_1_argument (XDR *xdrs, escalar3d_1_argument *objp)
{
	 if (!xdr_vect3D (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect3D (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_vectorial3d_1_argument (XDR *xdrs, vectorial3d_1_argument *objp)
{
	 if (!xdr_vect3D (xdrs, &objp->arg1))
		 return FALSE;
	 if (!xdr_vect3D (xdrs, &objp->arg2))
		 return FALSE;
	return TRUE;
}
