/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calc.h"


void
calcprog_1(double a, char *operador, double b, char *host)
{
	CLIENT *clnt;
	double  *resultado;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCPROG, CALCVER, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if(strcmp(operador, "+") == 0)
	{
		printf("Sumando\n");
		resultado = sumar_1(a, b, clnt);
	}
	else if (strcmp(operador, "-") == 0)
	{
		resultado = restar_1(a, b, clnt);
	}
	else if (strcmp(operador, "x") == 0)
	{
		resultado = multiplicar_1(a, b, clnt);
	}
	else if (strcmp(operador, "/") == 0)
	{
		resultado = dividir_1(a, b, clnt);
	}
	else
	{
		printf("Operador no valido");
	}
	
	if (resultado == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("Operación: %g %s %g = %g\n", a, operador, b, *resultado);

#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	double first, second;
	char *operator;

	if (argc < 5) {
		printf ("usage: %s <server_host> <first_number> <operator> <second_number>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	first = atof(argv[2]);
	operator = argv[3];
	second = atof(argv[4]);
	
	calcprog_1 (first, operator, second, host);
exit (0);
}